name: Build ESP32 EXE

on:
    push:
        branches: [main]
        tags:
            - "debug"
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies from requirements.txt
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install nuitka

            - name: Build with Nuitka
              run: |
                  python -m nuitka `
                    --onefile `
                    --show-progress `
                    --remove-output `
                    --lto=no `
                    --assume-yes-for-downloads `
                    --jobs=12 `
                    --output-dir=output `
                    --output-filename=ESP32-debug.exe `
                    --windows-icon-from-ico=src/res/icons/favicon.ico `
                    --plugin-enable=pyqt5 `
                    --include-package=algorithms.SecureEditor `
                    --include-package=template `
                    --include-module=mod.Fluent3Icon `
                    --include-data-dir=src/mod/font=mod/font `
                    --include-data-dir=src/log=log `
                    --include-data-dir=src/res=res `
                    src/mainWindows.py

            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: nuitka-executable
                  path: output/ESP32-debug.exe
