name: Build and Release ESP32 EXE

on:
    push:
        tags:
            - "v*" # 触发规则：当你推送 v1.0.0、v2.3.1 这样的 tag 时触发
    workflow_dispatch: # 也可以手动触发

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install nuitka

            - name: Ensure required directories exist
              run: |
                  if not exist src\log mkdir src\log
                  if not exist src\res mkdir src\res
                  if not exist src\mod\font mkdir src\mod\font

            - name: Build with Nuitka
              run: |
                  python -m nuitka `
                    --onefile `
                    --show-progress `
                    --remove-output `
                    --lto=no `
                    --assume-yes-for-downloads `
                    --jobs=12 `
                    --output-dir=output `
                    --output-filename=ESP32-debug.exe `
                    --windows-icon-from-ico=src/res/icons/favicon.ico `
                    --plugin-enable=pyqt5 `
                    --include-package=algorithms.SecureEditor `
                    --include-package=template `
                    --include-module=mod.Fluent3Icon `
                    --include-data-dir=src/mod/font=mod/font `
                    --include-data-dir=src/log=log `
                    --include-data-dir=src/res=res `
                    src/mainWindows.py
                    --windows-console-mode=disable

            - name: Upload to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: output/ESP32.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
