name: Build and Release ESP32 EXE

on:
  push:
    tags:
      - "v*" # 推送 tag 时触发
  workflow_dispatch: # 可手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build with Nuitka
        run: |
          python -m nuitka `
            --onefile `
            --show-progress `
            --remove-output `
            --lto=no `
            --assume-yes-for-downloads `
            --jobs=12 `
            --output-dir=output `
            --output-filename=ESP32.exe `
            --windows-icon-from-ico=src/res/icons/favicon.ico `
            --plugin-enable=pyqt5 `
            --include-package=algorithms.SecureEditor `
            --include-package=template `
            --include-module=mod.Fluent3Icon `
            --include-data-dir=src/mod/font=mod/font `
            --include-data-dir=src/log=log `
            --include-data-dir=src/res=res `
            --windows-console-mode=disable `
            src/mainWindows.py

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/ESP32.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
